# Generated by Django 4.2.5 on 2023-09-12 04:39

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Operacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('num1', models.FloatField()),
                ('num2', models.FloatField()),
                ('operacion', models.CharField(choices=[('suma', 'Suma'), ('resta', 'Resta'), ('multiplicacion', 'Multiplicación')], max_length=15)),
                ('resultado', models.FloatField(blank=True, null=True)),
            ],
        ),
    ]
